version: '3.7'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
#    volumes:
        
    environment: 
        - POSTGRES_DB=hack_vtb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    restart: always
    network_mode: "host"
  web:
    build:
      context: .
      dockerfile: ./Docker/web/Dockerfile
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hack_vtb
      - SERVER_PORT=80
    restart: always
    network_mode: "host"