"""empty message

Revision ID: 1e0387f22109
Revises: 
Create Date: 2022-10-07 21:49:43.818524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0387f22109'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__categories')),
    sa.UniqueConstraint('id', name=op.f('uq__categories__id'))
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck__products__check_price')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__products')),
    sa.UniqueConstraint('id', name=op.f('uq__products__id'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=15), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('phone', sa.CHAR(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('id', name=op.f('uq__users__id'))
    )
    op.create_table('product_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk__product_categories__category_id__categories')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk__product_categories__product_id__products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__product_categories')),
    sa.UniqueConstraint('id', name=op.f('uq__product_categories__id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_categories')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('categories')
    # ### end Alembic commands ###
