"""empty message

Revision ID: 237da77e0f87
Revises: 8aafeded49dd
Create Date: 2022-10-09 01:06:12.801475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237da77e0f87'
down_revision = '8aafeded49dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('photo', sa.VARCHAR(length=255), nullable=False))
    op.create_unique_constraint(op.f('uq__events__id'), 'events', ['id'])
    op.create_unique_constraint(op.f('uq__my_events__id'), 'my_events', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__my_events__id'), 'my_events', type_='unique')
    op.drop_constraint(op.f('uq__events__id'), 'events', type_='unique')
    op.drop_column('events', 'photo')
    # ### end Alembic commands ###
