"""empty message

Revision ID: 24438e527d29
Revises: 4e844f060a43
Create Date: 2022-10-09 02:14:45.294729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24438e527d29'
down_revision = '4e844f060a43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_events', sa.Column('condition', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_events', 'condition')
    # ### end Alembic commands ###
