"""empty message

Revision ID: 4e844f060a43
Revises: 949c6fcb8fcd
Create Date: 2022-10-09 01:46:14.018273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e844f060a43'
down_revision = '949c6fcb8fcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date_end', postgresql.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'date_end')
    # ### end Alembic commands ###
