"""empty message

Revision ID: 8aafeded49dd
Revises: e2b07252a429
Create Date: 2022-10-08 15:24:11.969029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8aafeded49dd"
down_revision = "e2b07252a429"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("descriotion", sa.VARCHAR(length=255), nullable=False),
        sa.Column("price", sa.FLOAT(), nullable=False),
        sa.Column("type", sa.VARCHAR(length=12), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__events")),
        sa.UniqueConstraint("id", name=op.f("uq__events__id")),
    )
    op.create_table(
        "my_events",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("events_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["events_id"], ["events.id"], name=op.f("fk__my_events__events_id__events")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk__my_events__user_id__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__my_events")),
        sa.UniqueConstraint("id", name=op.f("uq__my_events__id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("my_events")
    op.drop_table("events")
    # ### end Alembic commands ###
