"""empty message

Revision ID: 949c6fcb8fcd
Revises: 237da77e0f87
Create Date: 2022-10-09 01:14:42.201527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949c6fcb8fcd'
down_revision = '237da77e0f87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('author_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(op.f('fk__events__author_id__users'), 'events', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__events__author_id__users'), 'events', type_='foreignkey')
    op.drop_column('events', 'author_id')
    # ### end Alembic commands ###
