"""empty message

Revision ID: 9668768e8ed5
Revises: 1e0387f22109
Create Date: 2022-10-07 22:42:54.125777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9668768e8ed5'
down_revision = '1e0387f22109'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__categories__id'), 'categories', ['id'])
    op.create_unique_constraint(op.f('uq__product_categories__id'), 'product_categories', ['id'])
    op.add_column('products', sa.Column('photo', sa.VARCHAR(length=255), nullable=False))
    op.create_unique_constraint(op.f('uq__products__id'), 'products', ['id'])
    op.add_column('users', sa.Column('wallet_private', sa.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('wallet_public', sa.VARCHAR(length=255), nullable=False))
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__id'), 'users', type_='unique')
    op.drop_column('users', 'wallet_public')
    op.drop_column('users', 'wallet_private')
    op.drop_constraint(op.f('uq__products__id'), 'products', type_='unique')
    op.drop_column('products', 'photo')
    op.drop_constraint(op.f('uq__product_categories__id'), 'product_categories', type_='unique')
    op.drop_constraint(op.f('uq__categories__id'), 'categories', type_='unique')
    # ### end Alembic commands ###
