"""empty message

Revision ID: d273105942bb
Revises: 9668768e8ed5
Create Date: 2022-10-08 00:54:58.952756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d273105942bb"
down_revision = "9668768e8ed5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("nickname", sa.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "nickname")
    # ### end Alembic commands ###
